default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin

variables:
  DOCKER_IMAGE: $REGISTRY_USER/$CI_PROJECT_NAME

stages:
  - test
  - build
  # - deploy

test:
  stage: test
  image: node:18-alpine
  before_script: []
  script:
    - npm install
    - npm run lint --no-warn-ignored
  allow_failure: false
  only:
    - tags # Run only on merge requests

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - tags

# deploy:
#   stage: deploy
#   script:
#     - docker stop $$CI_PROJECT_NAME || true
#     - docker rm $$CI_PROJECT_NAME || true
#     - docker pull $DOCKER_IMAGE:latest
#     - |
#       docker run -d -p 3000:3000 \
#       -e API_PORT=$API_PORT \
#       -e NODE_ENV=$NODE_ENV \
#       -e JWT_SECRET=$JWT_SECRET \
#       -e DB_URL=$DB_URL \
#       -e CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
#       -e CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
#       -e CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET \
#       --name $$CI_PROJECT_NAME $DOCKER_IMAGE:latest
#   only:
#     - tags
